=== panbasten/BA/report/FCTest/chart/web/schemas/chartDefine.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 (http://www.altova.com) by wangqzh (yonyou) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="chartDefine">
		<xs:annotation>
			<xs:documentation>统计图封装定义</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="icon"/>
				<xs:element ref="propertyGroupDefines"/>
				<xs:element name="defaultSetting" type="defaultSettingdefine" minOccurs="1" maxOccurs="unbounded"/>
				<xs:element name="nodatadefaultSetting" type="defaultSettingdefine"  minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="apiDefines"/>
				<xs:element ref="eventDefines"/>
			</xs:sequence>
			<xs:attribute name="category" type="xs:string" use="required"/>
			<xs:attribute name="type" type="xs:string" use="required"/>
			<xs:attribute name="code" type="xs:string" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="index" type="xs:string" use="required"/>
			<xs:attribute name="width" type="xs:string" use="required"/>
			<xs:attribute name="height" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="propertyGroupDefine" type="propertyGroupDefineType"/>
	<xs:element name="propertyDefine">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ConstraintTerm" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="name" type="xs:string" use="required"/>
						<xs:attribute name="value" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attributeGroup ref="PGAttributes"/>
			<xs:attribute name="range" type="xs:string" use="optional"/>
			<xs:attribute name="repeatable" type="xs:boolean" use="optional" default="false"/>
			<xs:attribute name="generate" type="xs:boolean" use="optional" default="true"/>
			<xs:attribute name="hide" type="xs:boolean" use="optional" default="false"/>
			<xs:attribute name="isNLS" type="xs:boolean" use="optional" default="false"/>
			<xs:attribute name="relativeChange" type="xs:boolean"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="property">
		<xs:complexType>
			<xs:attribute name="code" type="xs:string" use="optional"/>
			<xs:attribute name="refCode" type="xs:string" use="required"/>
			<xs:attribute name="mulCode" type="xs:string"/>
			<xs:attribute name="value" type="xs:string" use="required"/>
			<xs:attribute name="generate" type="xs:boolean" use="optional" default="true"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="parameter">
		<xs:complexType/>
	</xs:element>
	<xs:element name="eventDefines">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="eventDefine" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="input" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="code" type="xs:string" use="required"/>
									<xs:attribute name="name" type="xs:string" use="required"/>
									<xs:attribute name="typeClassName" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="code" type="xs:string" use="required"/>
						<xs:attribute name="name" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="apiDefines">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="apiDefine" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="input" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="code" type="xs:string" use="required"/>
									<xs:attribute name="name" type="xs:string" use="required"/>
									<xs:attribute name="typeClassName" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="output">
								<xs:complexType>
									<xs:attribute name="typeClassName" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="code" type="xs:string" use="required"/>
						<xs:attribute name="name" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="includeApis" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="datasets">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="dataset" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="header" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="cell" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="code" type="xs:string" use="required"/>
												<xs:attribute name="mulCode" type="xs:string"/>
												<xs:attribute name="name" type="xs:string" use="required"/>
												<xs:attribute name="type" type="xs:string" use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="body" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="row" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="cell" minOccurs="0" maxOccurs="unbounded">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="columnSimpleType">
																	<xs:attribute name="code" type="xs:string"/>
																	<xs:attribute name="refCode" type="xs:string" use="required"/>
																	<xs:attribute name="isAll">
																		<xs:simpleType>
																			<xs:restriction base="xs:string">
																				<xs:enumeration value="true"/>
																				<xs:enumeration value="false"/>
																			</xs:restriction>
																		</xs:simpleType>
																	</xs:attribute>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="code" type="xs:string"/>
												<xs:attribute name="name" type="xs:string"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="code" type="xs:string"/>
									<xs:attribute name="name" type="xs:string"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="code" type="xs:string" use="required"/>
						<xs:attribute name="mulCode" type="xs:string"/>
						<xs:attribute name="name" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:attributeGroup name="PGAttributes">
		<xs:attribute name="code" type="xs:string" use="required"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="type" type="xs:string" use="optional"/>
		<xs:attribute name="editor" type="xs:string" use="optional"/>
		<xs:attribute name="description" type="xs:string" use="optional"/>
	</xs:attributeGroup>
	<xs:complexType name="defaultSettingdefine">
		
			<xs:sequence>
				<xs:element name="propertyGroup" type="propertyGroupType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="styleGroup" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="property" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
						<xs:attribute name="code" type="xs:string" use="required"/>
						<xs:attribute name="refCode" type="xs:string" use="required"/>
						<xs:attribute name="applyObject" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="userDivisionPropertyGroup" type="propertyGroupType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="autoDivisionPropertyGroup" type="propertyGroupType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="categoriesPropertyGroup" type="propertyGroupType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="warningPropertyGroup" type="propertyGroupType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="rangeColorPropertyGroup" type="propertyGroupType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="dataBindingRefGroup" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="property" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
						<xs:attribute name="code" type="xs:string" use="required"/>
						<xs:attribute name="refCode" type="xs:string" use="required"/>
						<xs:attribute name="datasetCode" type="xs:string" use="required"/>
						<xs:attribute name="columnCode" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="categorieAxises" minOccurs="0">
					<xs:complexType>
						<xs:choice>
							<xs:element name="category" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="code" type="xs:string" use="required"/>
									<xs:attribute name="datasetCode" type="xs:string" use="required"/>
									<xs:attribute name="columnCode" type="xs:string" use="required"/>
									<xs:attribute name="order" type="xs:string" use="optional"/>
									<xs:attribute name="hasOperate" use="optional" default="false">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true"/>
												<xs:enumeration value="false"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:choice>
					</xs:complexType>
				</xs:element>
				<xs:element name="seriesAxises">
					<xs:complexType>
						<xs:choice>
							<xs:element name="series" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="code" type="xs:string" use="optional"/>
									<xs:attribute name="datasetCode" type="xs:string" use="required"/>
									<xs:attribute name="columnCode" type="xs:string" use="required"/>
									<xs:attribute name="isMeasure" use="optional" default="true">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="false"/>
												<xs:enumeration value="true"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="order" type="xs:string" use="optional"/>
									<xs:attribute name="hasOperate" use="optional" default="false">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true"/>
												<xs:enumeration value="false"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="xySeries" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="code" type="xs:string" use="required"/>
									<xs:attribute name="datasetCode" type="xs:string" use="required"/>
									<xs:attribute name="xcolumnCode" type="xs:string" use="required"/>
									<xs:attribute name="ycolumnCode" type="xs:string" use="required"/>
									<xs:attribute name="isMeasure" use="optional" default="true">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="false"/>
												<xs:enumeration value="true"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="order" type="xs:string" use="optional"/>
									<xs:attribute name="hasOperate" use="optional" default="false">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true"/>
												<xs:enumeration value="false"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="xyzSeries" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="code" type="xs:string" use="required"/>
									<xs:attribute name="datasetCode" type="xs:string" use="required"/>
									<xs:attribute name="xcolumnCode" type="xs:string" use="required"/>
									<xs:attribute name="ycolumnCode" type="xs:string" use="required"/>
									<xs:attribute name="zcolumnCode" type="xs:string" use="required"/>
									<xs:attribute name="namecolumnCode" type="xs:string" use="required"/>
									<xs:attribute name="isMeasure" use="optional" default="true">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="false"/>
												<xs:enumeration value="true"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="order" type="xs:string" use="optional"/>
									<xs:attribute name="hasOperate" use="optional" default="false">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true"/>
												<xs:enumeration value="false"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="stackSeries" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="item" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="code" type="xs:string"/>
												<xs:attribute name="datasetCode" type="xs:string" use="required"/>
												<xs:attribute name="columnCode" type="xs:string" use="required"/>
												<xs:attribute name="isMeasure" use="optional" default="true">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:enumeration value="false"/>
															<xs:enumeration value="true"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="order" type="xs:string" use="optional"/>
												<xs:attribute name="hasOperate" use="optional" default="false">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:enumeration value="true"/>
															<xs:enumeration value="false"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="code" type="xs:string" use="required"/>
									<xs:attribute name="name" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:choice>
					</xs:complexType>
				</xs:element>
				<xs:element ref="datasets"/>
			</xs:sequence>
			<xs:attribute name="themeCode" type="xs:string" use="required"/>
		
	</xs:complexType>
	<xs:element name="propertyGroupDefines">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="propertyGroupDefine" maxOccurs="unbounded"/>
				<xs:element name="dataBindingGroupDefine" maxOccurs="unbounded">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="propertyGroupDefineType">
								<xs:attribute name="bindingGroup" type="xs:string" use="required"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="styleGroupDefine" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="applyObject" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="code" type="xs:string" use="required"/>
									<xs:attribute name="name" type="xs:string" use="required"/>
									<xs:attribute name="includeGroups" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="code" type="xs:string" use="required"/>
						<xs:attribute name="name" type="xs:string" use="required"/>
						<xs:attribute name="type" type="xs:string" use="required"/>
						<xs:attribute name="rawType" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="includeGroups"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="icon">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="littleIcon" type="xs:string"/>
				<xs:element name="mouseOverIcon" type="xs:string"/>
				<xs:element name="pressedIcon" type="xs:string"/>
				<xs:element name="bigIcon" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="columnSimpleType">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<xs:complexType name="propertyGroupDefineType">
		<xs:sequence>
			<xs:element ref="propertyDefine" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attributeGroup ref="PGAttributes"/>
		<xs:attribute name="assorrtment" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="property"/>
					<xs:enumeration value="style"/>
					<xs:enumeration value="trendline"/>
					<xs:enumeration value="vline"/>
					<xs:enumeration value="dataset"/>
					<xs:enumeration value="series"/>
					<xs:enumeration value="category"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="repeatable" type="xs:boolean"/>
		<xs:attribute name="relativeChange" type="xs:boolean"/>
	</xs:complexType>
	<xs:complexType name="propertyGroupType">
		<xs:sequence>
			<xs:element ref="property" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="refCode" type="xs:string" use="required"/>
	</xs:complexType>
</xs:schema>

=== panbasten/BA/report/FCTest/chart/web/chartDefines/MSBar2D/chartDefine.xml
<?xml version="1.0" encoding="utf-8"?>

<chartDefine xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" index="020243" width="400" height="300" code="MSBar2D" name="{10502004-0406}={条形图}" category="{10502004-0365}={基本统计图}" type="{10502004-0406}={条形图}" xsi:noNamespaceSchemaLocation="../../schemas/chartDefine.xsd">  
  <icon> 
    <littleIcon>little.png</littleIcon>  
    <mouseOverIcon>little.png</mouseOverIcon>  
    <pressedIcon>little.png</pressedIcon>  
    <bigIcon>little.png</bigIcon> 
  </icon>  
  <propertyGroupDefines includeGroups="FC_COMPRESS_SPACE,BQ_BEHAVIOR,FC_TITLES_AND_AXIS_NAMES,FC_DATA_PLOT_COSMETICS,FC_CHART_PADDING_AND_MARGINS,FC_COMMON_FUNCTIONAL,FC_LEGEND_PROPERTIES,FC_TOOL_TIP,FC_DIVISIONAL_LINES_AND_GRIDS,FC_FONT_PROPERTIES,FC_NUMBER_FORMATTING,FC_CANVAS_COSMETICS,FC_CHARTDATA_COSMETICS,FC_STYLE_FONT,FC_ANCHORS,FC_TREND_LINES,FC_VERTICAL_TREND_LINES">
    <propertyGroupDefine code="FC_COMPRESS_SPACE" name="压缩空行"/>
    <propertyGroupDefine code="FC_TITLES_AND_AXIS_NAMES" name="{10502004-0123}={标题和轴名称}"/>  
    <propertyGroupDefine code="FC_LEGEND_PROPERTIES" name="{10502004-0146}={图例}"/>  
    <propertyGroupDefine code="FC_TOOL_TIP" name="{10502004-0147}={悬浮提示}"> 
      <propertyDefine code="seriesNameInToolTip" name="{10502004-0148}={显示系列名}" type="toolTipcategory" description="{10502004-0149}={(seriesNameInToolTip) 是否在提示框中显示序列名称}"/>  
      <propertyDefine code="categoryNameInToolTip" name="{10502004-0150}={显示分类轴}" type="toolTipcategory" generate="false" description="{10502004-0151}={(categoryNameInToolTip) 是否显示分类轴}"/> 
   	  <propertyDefine code="scategoryNameInToolTip" name="显示次分类轴" type="sCategoryChkEditor" generate="false" description="{10502004-0151}={(categoryNameInToolTip) 是否显示次分类轴}"/>
    </propertyGroupDefine>  
    <propertyGroupDefine code="FC_STYLE_FONT" name="{10502004-0154}={字体样式}"/>  
    <propertyGroupDefine code="FC_DIVISIONAL_LINES_AND_GRIDS" name="{10502004-0153}={网格线}"> 
      <propertyDefine code="showAlternateVGridColor" name="{10502004-0278}={显示纵向交替色}" type="boolenEditMode" description="{10502004-0278}={显示纵向交替色}"/>  
      <propertyDefine code="alternateVGridColor" name="{10502004-0279}={纵向交替色}" type="color" description="{10502004-0279}={纵向交替色}"/> 
    </propertyGroupDefine>  
    <propertyGroupDefine code="FC_ANCHORS" name="{10502004-0283}={锚点外观}"/>  
    <propertyGroupDefine code="FC_DATA_PLOT_COSMETICS" name="{10502004-0098}={数据外观}"> 
      <propertyDefine code="plotGradientColor" name="{10502004-0967}={显示渐变色}" type="gradientEditMode" description="{10502004-0408}={(plotGradientColor) 渐变色}"/>  
      <propertyDefine code="paletteColors" name="{10502004-0366}={序列颜色}" type="textEditMode" description="{10502004-0367}={(paletteColors) 序列颜色}"/> 
    </propertyGroupDefine>  
    <propertyGroupDefine code="FC_COMMON_FUNCTIONAL" name="{10502004-0155}={通用功能}" type="group"> 
      <propertyDefine code="showLabels" name="{10502004-0173}={显示标签}" type="boolenEditMode" description="{10502004-0241}={(showLabels) 是否显示 x 轴标签文字}"/>  
      <propertyDefine code="labelDisplay" name="{10502004-0242}={标签显示方式}" type="enumEditMode" description="{10502004-0243}={(labelDisplay) 选取标签的显示方式}"> 
        <ConstraintTerm name="{10502004-0244}={默认}" value="AUTO"/>  
        <ConstraintTerm name="{10502004-0245}={折叠}" value="WRAP"/>  
        <ConstraintTerm name="{10502004-0246}={堆积}" value="STAGGER"/>  
        <ConstraintTerm name="{10502004-0247}={旋转}" value="ROTATE"/>  
        <ConstraintTerm name="{10502004-0248}={无}" value="NONE"/> 
      </propertyDefine>  
      <propertyDefine code="useEllipsesWhenOverflow" name="{10502004-0103}={标签过长省略}" type="boolenEditMode" description="{10502004-0288}={(useEllipsesWhenOverflow) 当标签文字过长时, 使用省略号表示无法显示的部分}"/>  
      <propertyDefine code="showYAxisValues" name="{10502004-0173}={显示标签}" type="boolenEditMode" description="{10502004-0249}={(showYAxisValues) 设置是否显示Y轴上面的值}"/>  
      <propertyDefine code="showLimits" name="{10502004-0250}={显示极值标签}" type="boolenEditMode" description="{10502004-0251}={(showLimits) 设置是否在Y轴显示极限值}"/>  
      <propertyDefine code="showDivLineValues" name="{10502004-0289}={显示Y轴网格线标签}" type="boolenEditMode" description="{10502004-0290}={(showDivLineValues) 设置是否显示网格线值}"/>  
      <propertyDefine code="animation" name="{10502004-0191}={动画}" type="boolenEditMode" description="{10502004-0291}={(animation) 以动画方式显示图表}"/> 
    </propertyGroupDefine>  
    <propertyGroupDefine code="FC_CHARTDATA_COSMETICS" name="{10502004-0160}={图表区外观}"/>  
    <propertyGroupDefine code="FC_CANVAS_COSMETICS" name="{10502004-0161}={画布外观}"/>  
    <propertyGroupDefine code="FC_CHART_PADDING_AND_MARGINS" name="{10502004-0152}={对齐和缩进}"/>  
    <propertyGroupDefine code="FC_NUMBER_FORMATTING" name="{10502004-0162}={数字格式}"/>  
    <propertyGroupDefine code="FC_FONT_PROPERTIES" name="{10502004-0163}={字体属性}"/>  
    <propertyGroupDefine code="FC_TREND_LINES" name="{10502004-0294}={横向趋势线}" type="preWarningLine" repeatable="true" relativeChange="true"/>  
    <propertyGroupDefine code="FC_VERTICAL_TREND_LINES" name="{10502004-0295}={纵向趋势线}" type="groupLine" repeatable="true" relativeChange="true"/>  
    <propertyGroupDefine code="FC_VERTICAL_TREND_LINES_AUTOGROUP" name="{10502004-0296}={自动分组线}" type="autoGroupLine" repeatable="true" relativeChange="true"/>  
    <propertyGroupDefine code="BQ_DATASETS" name="{10502004-0297}={数据集}" type="datasets"/>  
    <propertyGroupDefine code="BQ_CATEGORY" name="{10502004-0180}={分类轴}" type="category"/>  
    <propertyGroupDefine code="BQ_SERIES" name="{10502004-0196}={系列}" type="series"/>  
    <propertyGroupDefine code="BQ_CATEGORY_X" name="{10502004-0298}={X轴}" type="single_category"/>  
    <propertyGroupDefine code="BQ_CATEGORY_Y" name="{10502004-0299}={Y轴}" type="single_category"/>  
    <propertyGroupDefine code="BQ_CATEGORY_Z" name="{10502004-0300}={Z轴}" type="single_category"/>  
    <propertyGroupDefine code="BQ_PARAMETER" name="{10502004-0097}={参数}" type="parameterEditMode"/>  
    <propertyGroupDefine code="BQ_BEHAVIOR" name="{10502004-0230}={行为}"/>  
    <propertyGroupDefine code="BQ_ALTNTVDIM" name="{10502004-0301}={切换维度}" type="altntvDim"/>  
    <propertyGroupDefine code="BQ_ALTNTVMEAS" name="{10502004-0302}={切换指标}" type="altntvMeas"/>  
    <dataBindingGroupDefine code="BQ_DATABINDING" name="{10502004-0172}={系列详细设置}" bindingGroup="series"> 
      <propertyDefine code="showValues" name="{10502004-0173}={显示标签}" type="boolenEditMode" description="{10502004-0174}={(showValues) 设置是否在图上显示数值}"/>  
      <propertyDefine code="color" name="{10502004-0029}={颜色}" type="color" description="{10502004-0175}={(color) 序列的颜色}"/>  
      <propertyDefine code="alpha" name="{10502004-0091}={透明度}" type="transparencyEditMode" range="0~100" description="{10502004-0176}={(alpha) Alpha 颜色值, 取值范围 0~100}"/>  
      <propertyDefine code="dashed" name="{10502004-0033}={虚线}" type="boolenEditMode" description="{10502004-0034}={(dashed) 启用虚线}"/>
      <propertyDefine code="showPCategory" name="显示分类轴" type="boolenEditMode" generate="false" description="{10502004-0149}={(seriesNameInToolTip) 是否在提示框中显示序列名称}"/>  
      <propertyDefine code="showSCategory" name="显示次分类轴" type="sCategoryChkEditor" generate="false" description="{10502004-0151}={(categoryNameInToolTip) 是否显示分类轴}"/> 
      <propertyDefine code="showValue" name="显示值" type="boolenEditMode" generate="false" description="{10502004-0151}={(categoryNameInToolTip) 是否显示分类轴}"/> 
      <propertyDefine code="showSeries" name="显示系列名称" type="boolenEditMode" generate="false" description="{10502004-0151}={(categoryNameInToolTip) 是否显示分类轴}"/> 
      <propertyDefine code="showInPercent" name="显示百分比" type="boolenEditMode" generate="false" description="{10502004-0151}={(categoryNameInToolTip) 是否显示分类轴}"/> 
      <propertyDefine code="sepChar" name="分隔符" type="textEditMode" generate="false" description="{10502004-0151}={(categoryNameInToolTip) 是否显示分类轴}"/> 
    </dataBindingGroupDefine>  
    <styleGroupDefine code="BQ_STYLEAPPLY" name="{10502004-0177}={样式应用}" type="fonts" rawType="font"> 
      <applyObject code="Caption" name="{10502004-0178}={标题}" includeGroups="FC_STYLE_FONT"/>  
      <applyObject code="Subcaption" name="{10502004-0179}={副标题}" includeGroups="FC_STYLE_FONT"/>  
      <applyObject code="Datalabels" name="{10502004-0180}={分类轴}" includeGroups="FC_STYLE_FONT"/>  
      <applyObject code="Legend" name="{10502004-0146}={图例}" includeGroups="FC_STYLE_FONT"/>  
      <applyObject code="Tooltip" name="{10502004-0016}={悬浮提示}" includeGroups="FC_STYLE_FONT"/>  
      <applyObject code="XAxisName" name="{10502004-0181}={X轴标题}" includeGroups="FC_STYLE_FONT"/>  
      <applyObject code="YAxisName" name="{10502004-0182}={Y轴标题}" includeGroups="FC_STYLE_FONT"/>  
      <applyObject code="DataValues" name="{10502004-0183}={数据标签}" includeGroups="FC_STYLE_FONT"/> 
    </styleGroupDefine> 
  </propertyGroupDefines>  
  <defaultSetting themeCode="default">   
    <propertyGroup refCode="FC_TITLES_AND_AXIS_NAMES"> 
      <property refCode="caption" value="{10502004-0406}={条形图}" mulCode="{10502004-0406}={条形图}"/> 
    </propertyGroup>  
    <propertyGroup refCode="FC_AUTODEFINE_AUTOGROUPLINE">
          <property refCode="labelPosition" value="1" generate="false"/>
	</propertyGroup>
    <propertyGroup refCode="FC_DATA_PLOT_COSMETICS"> 
      <property refCode="showPlotBorder" value="true"/>  
      <property refCode="plotBorderThickness" value="1"/>  
      <property refCode="plotBorderColor" value="cecccc"/>  
      <property refCode="plotGradientColor" value=" "/> 
    </propertyGroup>  
    <propertyGroup refCode="FC_COMMON_FUNCTIONAL"> 
      <property refCode="showLabels" value="1"/>  
      <property refCode="labelDisplay" value="AUTO"/>  
      <property refCode="showYAxisValues" value="1"/>  
      <property refCode="showLimits" value="1"/>  
      <property refCode="animation" value="1"/> 
    </propertyGroup>   
    <propertyGroup refCode="BQ_DATABINDING">
