=== panbasten/BA/report/FCTest/chart/web/schemas/propertyRepository.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 (http://www.altova.com) by abcde (abcde) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:altova="http://www.altova.com/xml-schema-extensions" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="propertyRepository">
		<xs:annotation>
			<xs:documentation>属性组集合包含定义</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="propertyGroupDefine" maxOccurs="unbounded">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="propertyGroupDefineType">
								<xs:attribute name="dataBindingPropertyGroupDefineCode" type="xs:string" use="optional"/>
								<xs:attribute name="dataBindingPropertyDefineCode" type="xs:string" use="optional"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:attributeGroup name="attributeDefine">
		<xs:attribute name="code" type="xs:string" use="required"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="type" type="xs:string" use="optional"/>
		<xs:attribute name="editorDefine" type="xs:string" use="optional"/>
		<xs:attribute name="description" type="xs:string" use="optional"/>
		<xs:attribute name="assorrtment" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="property"/>
					<xs:enumeration value="style"/>
					<xs:enumeration value="trendline"/>
					<xs:enumeration value="vline"/>
					<xs:enumeration value="dataset"/>
					<xs:enumeration value="series"/>
					<xs:enumeration value="category"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:attributeGroup>
	<xs:complexType name="propertyGroupDefineType">
		<xs:sequence>
			<xs:element name="propertyDefine" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="ConstraintTerm" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="name" type="xs:string" use="required"/>
								<xs:attribute name="value" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attributeGroup ref="attributeDefine"/>
					<xs:attribute name="repeatable" type="xs:boolean" use="optional" default="false"/>
					<xs:attribute name="generate" type="xs:boolean" use="optional" default="true"/>
					<xs:attribute name="range" use="optional">
						<xs:annotation>
							<xs:appinfo>
								<altova:exampleValues>
									<altova:example value="1-5"/>
								</altova:exampleValues>
							</xs:appinfo>
						</xs:annotation>
						<xs:simpleType>
							<xs:restriction base="xs:string"/>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="hide" type="xs:boolean" use="optional" default="false"/>
					<xs:attribute name="isNLS" type="xs:boolean" use="optional" default="false"/>
					<xs:attribute name="relativeChange" type="xs:boolean"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attributeGroup ref="attributeDefine"/>
		<xs:attribute name="repeatable" type="xs:boolean"/>
		<xs:attribute name="relativeChange" type="xs:boolean"/>
	</xs:complexType>
</xs:schema>

=== panbasten/BA/report/FCTest/chart/web/repository/propertyRepository.xml
<?xml version="1.0" encoding="utf-8"?>

<propertyRepository xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/propertyRepository.xsd">  
  <propertyGroupDefine code="FC_COMMON_FUNCTIONAL" name="{10502004-0155}={通用功能}"> 
    <propertyDefine code="animation" name="{10502004-0191}={动画}" type="boolenEditMode" description="{10502004-0291}={(animation) 以动画方式显示图表}"/>  
    <propertyDefine code="palette" name="{10502004-0631}={预置调色板}" type="paletteEditMode" range="1~5" description="{10502004-0632}={(palette) 选取预制调色板, 范围1~5}"/>  
    <propertyDefine code="paletteColors" name="{10502004-0633}={调色板颜色序列}" type="colorList" description="{10502004-0634}={(paletteColors) 调试板的颜色序列, 将依次应用到各个显示的数据图形上}"/>  
    <propertyDefine code="showLabels" name="{10502004-0635}={显示X轴标签}" type="boolenEditMode" description="{10502004-0241}={(showLabels) 是否显示 x 轴标签文字}"/>  
    <propertyDefine code="labelDisplay" name="{10502004-0242}={标签显示方式}" type="enumEditMode" description="{10502004-0243}={(labelDisplay) 选取标签的显示方式}"> 
      <ConstraintTerm name="{10502004-0244}={默认}" value="AUTO"/>  
      <ConstraintTerm name="{10502004-0245}={折叠}" value="WRAP"/>  
      <ConstraintTerm name="{10502004-0246}={堆积}" value="STAGGER"/>  
      <ConstraintTerm name="{10502004-0247}={旋转}" value="ROTATE"/>  
      <ConstraintTerm name="{10502004-0248}={无}" value="NONE"/> 
    </propertyDefine>  
    <propertyDefine code="useEllipsesWhenOverflow" name="{10502004-0103}={标签过长省略}" type="boolenEditMode" description="{10502004-0288}={(useEllipsesWhenOverflow) 当标签文字过长时, 使用省略号表示无法显示的部分}"/>  
    <propertyDefine code="rotateLabels" name="{10502004-0636}={X轴标签旋转显示}" type="boolenEditMode" description="{10502004-0637}={(rotateLabels) 是否以旋转方式显示标签}"/>  
    <propertyDefine code="slantLabels" name="{10502004-0638}={X轴标签倾斜显示}" type="boolenEditMode" description="{10502004-0639}={(slantLabels) 是否以倾斜方式显示标签}"/>  
    <propertyDefine code="labelStep" name="{10502004-0640}={X轴标签间隔显示}" type="integerEditMode" description="{10502004-0641}={(labelStep) 设置跳过若干个标签后, 显示下一个标签, 接收包括 1 以上的数字}"/>  
    <propertyDefine code="staggerLines" name="{10502004-0642}={标签交错显示}" type="integerEditMode" description="{10502004-0643}={(staggerLines) 以交错方式显示标签, 设置交错的行数, 接收包括 2 以上的数字}"/>  
    <propertyDefine code="rotateValues" name="{10502004-0644}={旋转数据标签}" type="boolenEditMode" description="{10502004-0645}={(rotateValues) 设置是否按旋转方式显示数值}"/>  
    <propertyDefine code="placeValuesInside" name="{10502004-0412}={内置数据标签}" type="boolenEditMode" description="{10502004-0432}={(placeValuesInside) 设置是否将数值显示在数据图形内部}"/>  
    <propertyDefine code="showYAxisValues" name="{10502004-0646}={显示Y轴标签}" type="boolenEditMode" description="{10502004-0249}={(showYAxisValues) 设置是否显示Y轴上面的值}"/>  
    <propertyDefine code="showLimits" name="{10502004-0647}={显示上限下限}" type="boolenEditMode" description="{10502004-0251}={(showLimits) 设置是否在Y轴显示极限值}"/>  
    <propertyDefine code="showDivLineValues" name="{10502004-0289}={显示Y轴网格线标签}" type="boolenEditMode" description="{10502004-0290}={(showDivLineValues) 设置是否显示网格线值}"/>  
    <propertyDefine code="yAxisValuesStep" name="{10502004-0648}={显示Y轴网格线标签间隔}" type="integerEditMode" description="{10502004-0649}={(yAxisValuesStep) 设置跳过若干网格线, 显示下一个网格线值, 接收包括 1 以上的数字}"/>  
    <propertyDefine code="showShadow" name="{10502004-0650}={阴影}" type="boolenEditMode" description="{10502004-0651}={(showShadow) 设置是否为数据显示阴影}"/>  
    <propertyDefine code="rotateYAxisName" name="{10502004-0652}={旋转Y轴标题}" type="boolenEditMode" description="{10502004-0653}={(rotateYAxisName) 设置是否旋转 Y 轴名称}"/>  
    <propertyDefine code="yAxisNameWidth" name="{10502004-0654}={Y轴标题宽度}" type="integerEditMode" description="{10502004-0655}={(yAxisNameWidth) Y 轴名称宽度}"/>  
    <propertyDefine code="yAxisMinValue" name="{10502004-0087}={刻度最小值}" type="paramTextEditor" description="{10502004-0589}={(yAxisMinValue) Y轴最小值}" relativeChange="true"/>  
    <propertyDefine code="yAxisMaxValue" name="{10502004-0089}={刻度最大值}" type="paramTextEditor" description="{10502004-0590}={(yAxisMaxValue) Y轴最大值}" relativeChange="true"/> 
  </propertyGroupDefine>  
  <propertyGroupDefine code="FC_VERTICAL_TREND_LINES_AUTOGROUP" name="{10502004-0296}={自动分组线}" type="autoGroupLine" repeatable="true"> 
    <propertyDefine code="showLabelBorder" name="{10502004-0371}={显示标签边框}" type="boolenEditMode" description="{10502004-0372}={(showLabelBorder) 显示标签边框}"/>  
    <propertyDefine code="linePosition" name="{10502004-0375}={线位置}" type="textEditMode" description="{10502004-0376}={(linePosition) 线位置}"/>  
    <propertyDefine code="labelPosition" name="{10502004-0377}={标签位置}" type="enumEditMode" description="{10502004-0378}={(labelPosition) 标签位置}"> 
      <ConstraintTerm name="{10502004-0379}={顶部}" value="0"/>  
      <ConstraintTerm name="{10502004-0380}={底部}" value="1"/> 
    </propertyDefine>  
    <propertyDefine code="color" name="{10502004-0029}={颜色}" type="color" description="{10502004-0030}={(color) 颜色}"/>  
    <propertyDefine code="thickness" name="{10502004-0031}={线宽}" type="enumEditMode" description="{10502004-0381}={(thickness) 使用的分组线宽度}"> 
      <ConstraintTerm name="1px" value="1"/>  
      <ConstraintTerm name="2px" value="2"/>  
      <ConstraintTerm name="3px" value="3"/>  
      <ConstraintTerm name="4px" value="4"/>  
      <ConstraintTerm name="5px" value="5"/> 
    </propertyDefine>  
    <propertyDefine code="alpha" name="{10502004-0091}={透明度}" type="transparencyEditMode" description="{10502004-0382}={(alpha)透明度}"/>  
    <propertyDefine code="dashed" name="{10502004-0033}={虚线}" type="boolenEditMode" description="{10502004-0034}={(dashed) 启用虚线}"/>  
    <propertyDefine code="dashLen" name="{10502004-0035}={虚线宽度}" type="unitName_integerEditMode" description="{10502004-0036}={(dashLen) 虚线的宽度}"/>  
    <propertyDefine code="dashGap" name="{10502004-0037}={虚线间隔}" type="unitName_integerEditMode" description="{10502004-0038}={(dashGap) 虚线的间隔宽度}"/> 
  </propertyGroupDefine>  
  <propertyGroupDefine code="FC_QUADRANT" name="{10502004-0252}={象限}"> 
    <propertyDefine code="drawQuadrant" name="{10502004-0329}={显示象限}" type="boolenEditMode" description="{10502004-0656}={(drawQuadrant) 是否显示象限}"/>  
    <propertyDefine code="quadrantXVal" name="{10502004-0657}={垂直象限线位置}" type="integerEditMode" description="{10502004-0658}={(quadrantXVal) 垂直象限线位置}"/>  
    <propertyDefine code="quadrantYVal" name="{10502004-0659}={水平象限线位置}" type="integerEditMode" description="{10502004-0660}={(quadrantYVal) 水平象限线位置}"/>  
    <propertyDefine code="quadrantLineAlpha" name="{10502004-0661}={象限透明度}" type="transparencyEditMode" description="{10502004-0662}={(quadrantLineAlpha)象限透明度}"/>  
    <propertyDefine code="quadrantLineColor" name="{10502004-0663}={象限颜色}" type="color" description="{10502004-0664}={(quadrantLineColor) 颜色}"/>  
    <propertyDefine code="quadrantLineThickness" name="{10502004-0665}={象限线宽}" type="enumEditMode" range="1~5" description="{10502004-0666}={(quadrantLineThickness) 象限的宽度, 取值范围 1~5}"> 
      <ConstraintTerm name="1px" value="1"/>  
      <ConstraintTerm name="2px" value="2"/>  
      <ConstraintTerm name="3px" value="3"/>  
      <ConstraintTerm name="4px" value="4"/>  
      <ConstraintTerm name="5px" value="5"/> 
    </propertyDefine>  
    <propertyDefine code="quadrantLineIsDashed" name="{10502004-0033}={虚线}" type="boolenEditMode" description="{10502004-0667}={(quadrantLineIsDashed) 是否使用虚线垂直}"/>  
    <propertyDefine code="quadrantLineDashLen" name="{10502004-0582}={虚线中实线段长度}" type="unitName_integerEditMode" description="{10502004-0668}={(quadrantLineDashLen) 虚线的长度值, 像素为单位}"/>  
    <propertyDefine code="quadrantLineDashGap" name="{10502004-0584}={虚线中实线段间距}" type="unitName_integerEditMode" description="{10502004-0669}={(quadrantLineDashGap) 虚线间隔值, 像素为单位}"/> 
  </propertyGroupDefine>  
  <propertyGroupDefine code="FC_VERTICAL_LINES" name="{10502004-0253}={垂直线}"> 
    <propertyDefine code="verticalLineDashed" name="{10502004-0033}={虚线}" type="boolenEditMode" description="{10502004-0670}={(verticalLineDashed ) 是否使用虚线垂直}"/>  
    <propertyDefine code="verticalLineDashLen" name="{10502004-0582}={虚线中实线段长度}" type="unitName_integerEditMode" description="{10502004-0671}={(verticalLineDashLen) 虚线垂直线的长度值, 像素为单位}"/>  
    <propertyDefine code="verticalLineDashGap" name="{10502004-0584}={虚线中实线段间距}" type="unitName_integerEditMode" description="{10502004-0672}={(verticalLineDashGap) 虚线垂直线的间隔值, 像素为单位}"/>  
    <propertyDefine code="showVerticalLine" name="{10502004-0336}={显示垂直线}" type="boolenEditMode" description="{10502004-0673}={(showVerticalLine) 设置是否显示垂直线}"/>  
    <propertyDefine code="verticalLineAlpha" name="{10502004-0674}={垂直线透明度}" type="transparencyEditMode" description="{10502004-0675}={(verticalLineAlpha)垂直线透明度}"/>  
    <propertyDefine code="verticalLineColor" name="{10502004-0676}={垂直线颜色}" type="color" description="{10502004-0677}={(verticalLineColor ) 垂直线的颜色}"/>  
    <propertyDefine code="verticalLineThickness" name="{10502004-0678}={垂直线宽}" type="enumEditMode" range="1~5" description="{10502004-0679}={(verticalLineThickness ) 垂直线的宽度, 取值范围 1~5}"> 
      <ConstraintTerm name="1px" value="1"/>  
      <ConstraintTerm name="2px" value="2"/>  
      <ConstraintTerm name="3px" value="3"/>  
      <ConstraintTerm name="4px" value="4"/>  
      <ConstraintTerm name="5px" value="5"/> 
    </propertyDefine> 
  </propertyGroupDefine>  
  <propertyGroupDefine code="FW_COMMON_FUNCTIONAL" name="{10502004-0155}={通用功能}"> 
    <propertyDefine code="animation" name="{10502004-0191}={动画}" type="boolenEditMode" description="{10502004-0291}={(animation) 以动画方式显示图表}"/>  
    <propertyDefine code="palette" name="{10502004-0680}={调色板}" type="paletteEditMode" range="1~5" description="{10502004-0632}={(palette) 选取预制调色板, 范围1~5}"/>  
    <propertyDefine code="paletteThemeColor" name="{10502004-0681}={调色板风格颜色}" type="colorList" description="{10502004-0682}={(paletteThemeColor) 调试板的颜色序列, 将依次应用到各个显示的数据图形上}"/>
